# vkmin v0.1 -- C11 only, everywhere, including this build.

CC      ?= cc
BUILD   ?= build
GLSLANG ?= glslangValidator

# Maximum practical warning level, warnings as errors, static analysis in the
# normal build. If any of this is ever quietly turned off, defects accumulate
# from that moment on, so a regression here is urgent.
WARN := -std=c11 -Wall -Wextra -Wpedantic -Werror -Wshadow -Wstrict-prototypes \
        -Wmissing-prototypes -Wold-style-definition -Wvla -Wpointer-arith -Wundef \
        -Wformat=2 -Wdouble-promotion -Wwrite-strings -Wcast-align \
        -Winit-self -Wredundant-decls
ANALYZER ?= -fanalyzer
OPT      ?= -O2 -g
# SANITIZE=1 adds ASan + UBSan. Leak detection is off because the loader and
# GLFW own allocations that outlive us; everything else is on.
ifeq ($(SANITIZE),1)
SAN := -fsanitize=address,undefined -fno-omit-frame-pointer
endif
INCLUDES := -Isrc -Idemo -Ithird_party -I$(BUILD)
CFLAGS   := $(OPT) $(WARN) $(ANALYZER) $(SAN) $(INCLUDES)
LDLIBS   := -lvulkan -lm
GLFW_LIBS := $(shell pkg-config --libs glfw3 2>/dev/null || echo -lglfw)

# Third-party code is quarantined in its own translation units and compiled
# without our warning set: it is not ours to fix, and mixing it into the main
# build is how -Werror gets disabled for everything.
THIRD_PARTY_CFLAGS := -std=c11 $(OPT) -w $(SAN) $(INCLUDES)

SHADER_SRC := $(wildcard shaders/*.vert shaders/*.frag shaders/*.comp)
SPV        := $(patsubst shaders/%,$(BUILD)/%.spv,$(SHADER_SRC))
GLSL_FLAGS := -V --target-env vulkan1.3 -Isrc -Ishaders -P"\#extension GL_GOOGLE_include_directive : require"

CORE_OBJS := $(BUILD)/vkmin.o $(BUILD)/plat_glfw.o $(BUILD)/stb_bridge.o $(BUILD)/cvar.o

.PHONY: all clean test golden texture analyze tools
all: tools $(BUILD)/smoke
tools: $(BUILD)/imgdiff $(BUILD)/pngsolid $(BUILD)/mktex $(BUILD)/mat4_test

$(BUILD):
	@mkdir -p $(BUILD)

# --- shaders: compiled offline, embedded as uint32_t arrays. No runtime
# --- shader compiler, no file-path failure mode in the binary.
$(BUILD)/%.spv: shaders/% shaders/common.glsl src/shared.h | $(BUILD)
	$(GLSLANG) $(GLSL_FLAGS) $< -o $@

$(BUILD)/bin2c: tools/bin2c.c | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $<

$(BUILD)/shaders.h: $(SPV) $(BUILD)/bin2c
	@printf '/* generated by the build from the shaders directory; do not edit */\n' > $@
	@printf '#ifndef VKMIN_SHADERS_H\n#define VKMIN_SHADERS_H\n#include <stdint.h>\n\n' >> $@
	@for s in $(notdir $(SHADER_SRC)); do \
	    sym=$$(echo $$s | tr '.' '_')_spv; \
	    $(BUILD)/bin2c $(BUILD)/$$s.spv $$sym >> $@ || exit 1; \
	done
	@printf '#endif\n' >> $@

# --- objects
$(BUILD)/%.o: src/%.c src/vkmin.h src/shared.h src/plat.h src/stb_bridge.h src/cvar.h | $(BUILD)
	$(CC) $(CFLAGS) -c -o $@ $<

$(BUILD)/stb_bridge.o: src/stb_bridge.c src/stb_bridge.h | $(BUILD)
	$(CC) $(THIRD_PARTY_CFLAGS) -c -o $@ $<

$(BUILD)/smoke: tests/smoke.c $(BUILD)/shaders.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/imgdiff: tools/imgdiff.c $(BUILD)/stb_bridge.o | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $^ -lm

$(BUILD)/pngsolid: tools/pngsolid.c $(BUILD)/stb_bridge.o | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $^ -lm

$(BUILD)/mktex: tools/mktex.c $(BUILD)/stb_bridge.o | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $^ -lm

$(BUILD)/mat4_test: tests/mat4_test.c demo/mat4.h | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $< -lm

texture: $(BUILD)/mktex
	./$(BUILD)/mktex tests/assets/grid.png

test: all
	./tests/run_tests.sh

golden: all
	VKMIN_WRITE_GOLDEN=1 ./tests/run_tests.sh

# A second analyser finds different things than the first.
analyze:
	@command -v cppcheck >/dev/null || { echo "cppcheck not installed"; exit 1; }
	cppcheck --std=c11 --enable=warning,style,performance,portability \
	    --inline-suppr --error-exitcode=1 --quiet \
	    --suppress=missingIncludeSystem --suppress=missingInclude \
	    -Isrc -Idemo -I$(BUILD) -i third_party -i src/stb_bridge.c \
	    src demo tools tests

clean:
	rm -rf $(BUILD) tests/out
