# vkmin v0.1 -- C11 only, everywhere, including this build.

CC      ?= cc
BUILD   ?= build
GLSLANG ?= glslangValidator
SPIRV_VAL ?= spirv-val

# Maximum practical warning level, warnings as errors, static analysis in the
# normal build. If any of this is ever quietly turned off, defects accumulate
# from that moment on, so a regression here is urgent.
WARN := -std=c11 -Wall -Wextra -Wpedantic -Werror -Wshadow -Wstrict-prototypes \
        -Wmissing-prototypes -Wold-style-definition -Wvla -Wpointer-arith -Wundef \
        -Wformat=2 -Wdouble-promotion -Wwrite-strings -Wcast-align \
        -Winit-self -Wredundant-decls
ANALYZER ?= -fanalyzer
OPT      ?= -O2 -g
# SANITIZE=1 adds ASan + UBSan. Leak detection is off because the loader and
# GLFW own allocations that outlive us; everything else is on.
ifeq ($(SANITIZE),1)
SAN := -fsanitize=address,undefined -fno-omit-frame-pointer
endif
INCLUDES := -Isrc -Idemo -Ithird_party -I$(BUILD)
ifeq ($(OS),Windows_NT)
INCLUDES += -I$(subst \,/,$(VULKAN_SDK))/Include
endif
CFLAGS   = $(OPT) $(WARN) $(ANALYZER) $(SAN) $(INCLUDES) -MMD -MP -MT $@
LDLIBS   := -lvulkan -lm
ifeq ($(OS),Windows_NT)
LDLIBS := $(subst \,/,$(VULKAN_SDK))/Lib/vulkan-1.lib -lm
endif
GLFW_LIBS := $(shell pkg-config --libs glfw3 2>/dev/null || echo -lglfw)

# Third-party code is quarantined in its own translation units and compiled
# without our warning set: it is not ours to fix, and mixing it into the main
# build is how -Werror gets disabled for everything.
THIRD_PARTY_CFLAGS := -std=c11 $(OPT) -w $(SAN) $(INCLUDES)

SHADER_SRC := $(wildcard shaders/*.vert shaders/*.frag shaders/*.comp)
SPV        := $(patsubst shaders/%,$(BUILD)/%.spv,$(SHADER_SRC))
# SPIR-V 1.5 keeps discard as OpKill; newer compilers otherwise introduce
# the optional shaderDemoteToHelperInvocation feature without asking us.
GLSL_FLAGS := -V --target-env vulkan1.3 --target-env spirv1.5 -Isrc -Ishaders -P"\#extension GL_GOOGLE_include_directive : require"

CORE_OBJS := $(BUILD)/vkmin.o $(BUILD)/plat_glfw.o $(BUILD)/stb_bridge.o $(BUILD)/cvar.o $(BUILD)/ktx2.o $(BUILD)/scene.o $(BUILD)/render.o
ifeq ($(HEADLESS),1)
CFLAGS += -DVKMIN_NO_PLATFORM
CORE_OBJS := $(filter-out $(BUILD)/plat_glfw.o,$(CORE_OBJS))
GLFW_LIBS :=
endif

.PHONY: all clean test golden texture analyze tools validate-shaders
EXAMPLES := $(patsubst examples/%.c,$(BUILD)/ex_%,$(wildcard examples/*.c))

all: tools $(BUILD)/smoke $(BUILD)/pick $(BUILD)/corridor $(EXAMPLES)
include Makefile.sndmin
all: sndmin
test: sndmin-test $(BUILD)/sndmin_valley
test: $(BUILD)/sndmin_unison
$(BUILD)/sndmin_unison: examples/sndmin/06_unison.c examples/sndmin/demo.h $(CORE_OBJS) $(SND_OBJECTS) $(SND_BUILD)/sndmin_null.o
	$(CC) $(CFLAGS) -ffp-contract=off -DSNDMIN_VIDEO -o $@ $< $(CORE_OBJS) $(SND_OBJECTS) $(SND_BUILD)/sndmin_null.o $(LDLIBS) $(GLFW_LIBS)
.PHONY: sndmin-valley
sndmin-valley: $(BUILD)/sndmin_valley
$(BUILD)/sndmin_valley: examples/20_valley.c demo/valley_audio.h demo/valley_score.h $(BUILD)/shaders.h $(CORE_OBJS) $(SND_OBJECTS) $(SND_BUILD)/sndmin_null.o
	$(CC) $(CFLAGS) -ffp-contract=off -DSNDMIN_VALLEY -Iexamples -o $@ $< $(CORE_OBJS) $(SND_OBJECTS) $(SND_BUILD)/sndmin_null.o $(LDLIBS) $(GLFW_LIBS)
# Keep transitive includes honest, including standalone tools and examples.
# This follows the default target so dependency files cannot change it.
-include $(wildcard $(BUILD)/*.d)
tools: $(BUILD)/imgdiff $(BUILD)/mktex $(BUILD)/mat4_test $(BUILD)/cook $(BUILD)/handles $(BUILD)/spirv_test $(BUILD)/layout.comp.spv $(BUILD)/lifecycle $(BUILD)/heightfield
tools: $(BUILD)/reload $(BUILD)/reload.frag.spv $(BUILD)/journal
tools: $(BUILD)/outside

$(BUILD)/outside: tests/outside.c tests/process.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

tools: $(BUILD)/play_test

$(BUILD):
	@mkdir -p $(BUILD)

# --- shaders: compiled offline, embedded as uint32_t arrays. No runtime
# --- shader compiler, no file-path failure mode in the binary.
$(BUILD)/%.spv: shaders/% Makefile $(wildcard shaders/*.glsl shaders/lib/*.glsl) src/shared.h | $(BUILD)
	$(GLSLANG) $(GLSL_FLAGS) $< -o $@

$(BUILD)/bin2c: tools/bin2c.c | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $<

$(BUILD)/shaders.h: $(SPV) $(BUILD)/bin2c
	@printf '/* generated by the build from the shaders directory; do not edit */\n' > $@
	@printf '#ifndef VKMIN_SHADERS_H\n#define VKMIN_SHADERS_H\n#include <stdint.h>\n\n' >> $@
	@for s in $(notdir $(SHADER_SRC)); do \
	    sym=$$(echo $$s | tr '.' '_')_spv; \
	    $(BUILD)/bin2c $(BUILD)/$$s.spv $$sym >> $@ || exit 1; \
	done
	@printf '#endif\n' >> $@

# --- objects
$(BUILD)/%.o: src/%.c src/vkmin.h src/spirv.h src/shared.h src/plat.h src/stb_bridge.h src/cvar.h src/ktx2.h src/scene.h src/vkm_format.h src/render.h src/vkmin_math.h src/font.h $(BUILD)/shaders.h | $(BUILD)
	$(CC) $(CFLAGS) -c -o $@ $<

$(BUILD)/stb_bridge.o: src/stb_bridge.c src/stb_bridge.h | $(BUILD)
	$(CC) $(THIRD_PARTY_CFLAGS) -c -o $@ $<

$(BUILD)/smoke: tests/smoke.c $(BUILD)/shaders.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/pick: tests/pick.c demo/gamekit.h src/render.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -Iexamples -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/handles: tests/handles.c tests/process.h $(BUILD)/shaders.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/spirv_test: tests/spirv_test.c src/spirv.h $(BUILD)/shaders.h
	$(CC) $(CFLAGS) -o $@ $<

$(BUILD)/layout.comp.spv: tests/layout.comp Makefile | $(BUILD)
	$(GLSLANG) $(GLSL_FLAGS) $< -o $@

$(BUILD)/lifecycle: tests/lifecycle.c $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/heightfield: tests/heightfield.c tests/process.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/reload: tests/reload.c $(BUILD)/shaders.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/reload.frag.spv: tests/reload.frag Makefile | $(BUILD)
	$(GLSLANG) $(GLSL_FLAGS) $< -o $@

$(BUILD)/journal: tests/journal.c $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

# The examples are the tutorial and the tests: each builds alone against the
# header, and each produces a golden image in make test.
$(BUILD)/ex_%: examples/%.c examples/cube_data.h demo/gamekit.h demo/play.h demo/anim.h src/vkmin.h src/vkmin_math.h src/render.h $(BUILD)/shaders.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -Iexamples -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/corridor: demo/corridor.c demo/anim.h demo/gamekit.h src/render.h src/scene.h src/vkmin_math.h $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $< $(CORE_OBJS) $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/imgdiff: tools/imgdiff.c $(BUILD)/stb_bridge.o | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $^ -lm

$(BUILD)/mktex: tools/mktex.c $(BUILD)/stb_bridge.o | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $^ -lm

$(BUILD)/mat4_test: tests/mat4_test.c src/vkmin_math.h | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $< -lm

$(BUILD)/play_test: tests/play.c demo/play.h demo/gamekit.h demo/anim.h $(BUILD)/shaders.h
	$(CC) $(CFLAGS) -o $@ $< -lm

$(BUILD)/mkdemo: tools/mkdemo.c src/vkmin.h | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $< -lm

# The demo files are committed (tests/journals); `make demos` rewrites them.
.PHONY: demos
demos: $(BUILD)/mkdemo
	./$(BUILD)/mkdemo tests/journals

$(BUILD)/mkfont: tools/mkfont.c | $(BUILD)
	$(CC) $(THIRD_PARTY_CFLAGS) -o $@ $< -lm

# The baked font is committed (src/font.h) so the build has no font-file
# dependency; `make font` regenerates it from the system TTF.
FONT_TTF ?= /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
.PHONY: font
font: $(BUILD)/mkfont
	./$(BUILD)/mkfont $(FONT_TTF) 32 > src/font.h

$(BUILD)/cook_image.o: tools/cook_image.c tools/cook_image.h | $(BUILD)
	$(CC) $(THIRD_PARTY_CFLAGS) -Itools -c -o $@ $<

$(BUILD)/cook: tools/cook.c tools/cook_image.h src/vkm_format.h src/shared.h $(BUILD)/cook_image.o | $(BUILD)
	$(CC) $(CFLAGS) -Itools -Wno-unused-function -o $@ $< $(BUILD)/cook_image.o -lm

texture: $(BUILD)/mktex
	./$(BUILD)/mktex tests/assets/grid.png

# Static analysis is part of the test run, not a target someone remembers:
# a finding fails the build.
test: all analyze validate-shaders $(BUILD)/amalg_check
	./tests/run_tests.sh

validate-shaders: $(SPV) $(BUILD)/layout.comp.spv $(BUILD)/reload.frag.spv
	@for s in $^; do $(SPIRV_VAL) --target-env vulkan1.3 --scalar-block-layout $$s || exit 1; done

# The single-header form is generated, never edited, and must compile alone.
.PHONY: amalgamate
amalgamate: $(BUILD)/vkmin_single.h
$(BUILD)/vkmin_single.h: tools/amalgamate.sh src/shared.h src/vkmin.h src/spirv.h src/jrnl.h src/vkmin_math.h src/pack.h src/cvar.h src/cvar.c src/plat.h src/plat_glfw.c src/stb_bridge.h src/stb_bridge.c src/vkmin.c | $(BUILD)
	./tools/amalgamate.sh > $@
$(BUILD)/amalg_check: $(BUILD)/vkmin_single.h tests/amalg_check.c
	$(CC) -std=c11 -O1 -Wall -Wextra -Werror -Wno-unused-function $(INCLUDES) $(filter -DVKMIN_NO_PLATFORM,$(CFLAGS)) -o $@ tests/amalg_check.c $(LDLIBS) $(GLFW_LIBS)

golden: all
	VKMIN_WRITE_GOLDEN=1 ./tests/run_tests.sh

# A second analyser finds different things than the first. Missing cppcheck is
# a failure, not a skip: a check that silently vanishes is the failure mode.
analyze:
	@command -v cppcheck >/dev/null || { echo "cppcheck not installed; it is required by make test"; exit 1; }
	cppcheck --std=c11 --enable=warning,style,performance,portability \
	    --inline-suppr --error-exitcode=1 --quiet \
	    --suppress=missingIncludeSystem --suppress=missingInclude \
        -Isrc -Idemo -I$(BUILD) -i third_party -i src/stb_bridge.c -i src/sndmin_io.c -i src/sndmin_miniaudio.c -UVKMIN_NO_PLATFORM \
	    src demo tools tests examples

clean:
	rm -rf $(BUILD) tests/out
