# vkmin -- C11 only, everywhere, including this build.

CC      ?= cc
BUILD   ?= build
GLSLANG ?= glslangValidator

# Maximum practical warning level, warnings as errors, static analysis in the
# normal build. If any of this ever gets quietly turned off, errors accumulate
# from that moment on, so treat a regression here as urgent.
WARN := -std=c11 -Wall -Wextra -Wpedantic -Werror -Wshadow -Wstrict-prototypes \
        -Wmissing-prototypes -Wold-style-definition -Wvla -Wpointer-arith -Wundef \
        -Wformat=2 -Wdouble-promotion -Wwrite-strings -Wcast-align \
        -Winit-self -Wredundant-decls
ANALYZER ?= -fanalyzer
OPT      ?= -O2 -g
INCLUDES := -Isrc -Idemo -Ithird_party -I$(BUILD)
CFLAGS   := $(OPT) $(WARN) $(ANALYZER) $(INCLUDES)
LDLIBS   := -lvulkan -lm
GLFW_LIBS := $(shell pkg-config --libs glfw3 2>/dev/null || echo -lglfw)

# Third-party code is quarantined in its own translation unit and compiled
# without our warning set: it is not ours to fix, and mixing it into the main
# build is how -Werror gets disabled for everything.
THIRD_PARTY_CFLAGS := -std=c11 $(OPT) -w $(INCLUDES)

SHADERS := tri.vert tri.frag cube.vert cube_flat.frag cube_tex.frag
SPV     := $(addprefix $(BUILD)/,$(addsuffix .spv,$(SHADERS)))

CORE_OBJS := $(BUILD)/vkmin.o $(BUILD)/plat_glfw.o $(BUILD)/stb_bridge.o

.PHONY: all clean test golden texture analyze
all: $(BUILD)/cube $(BUILD)/imgdiff $(BUILD)/pngsolid $(BUILD)/mktex $(BUILD)/mat4_test

$(BUILD):
	@mkdir -p $(BUILD)

# --- shaders: compiled offline, embedded as uint32_t arrays. No runtime
# --- shader compiler and no file-path failure mode in the binary.
$(BUILD)/%.spv: shaders/% | $(BUILD)
	$(GLSLANG) -V --target-env vulkan1.3 $< -o $@

$(BUILD)/bin2c: tools/bin2c.c | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $<

$(BUILD)/shaders.h: $(SPV) $(BUILD)/bin2c
	@printf '/* generated by the build from the shaders directory; do not edit */\n' > $@
	@printf '#ifndef VKMIN_SHADERS_H\n#define VKMIN_SHADERS_H\n#include <stdint.h>\n\n' >> $@
	@for s in $(SHADERS); do \
	    sym=$$(echo $$s | tr '.' '_')_spv; \
	    $(BUILD)/bin2c $(BUILD)/$$s.spv $$sym >> $@ || exit 1; \
	done
	@printf '#endif\n' >> $@

# --- objects
$(BUILD)/vkmin.o: src/vkmin.c src/vkmin.h src/plat.h src/stb_bridge.h | $(BUILD)
	$(CC) $(CFLAGS) -c -o $@ $<

$(BUILD)/plat_glfw.o: src/plat_glfw.c src/plat.h | $(BUILD)
	$(CC) $(CFLAGS) -c -o $@ $<

$(BUILD)/stb_bridge.o: src/stb_bridge.c src/stb_bridge.h | $(BUILD)
	$(CC) $(THIRD_PARTY_CFLAGS) -c -o $@ $<

$(BUILD)/cube.o: demo/cube.c demo/mat4.h src/vkmin.h $(BUILD)/shaders.h | $(BUILD)
	$(CC) $(CFLAGS) -c -o $@ $<

$(BUILD)/cube: $(BUILD)/cube.o $(CORE_OBJS)
	$(CC) -o $@ $^ $(LDLIBS) $(GLFW_LIBS)

$(BUILD)/imgdiff: tools/imgdiff.c $(BUILD)/stb_bridge.o | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $^ -lm

$(BUILD)/pngsolid: tools/pngsolid.c $(BUILD)/stb_bridge.o | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $^ -lm

$(BUILD)/mktex: tools/mktex.c $(BUILD)/stb_bridge.o | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $^ -lm

$(BUILD)/mat4_test: tests/mat4_test.c demo/mat4.h | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $< -lm

texture: $(BUILD)/mktex
	./$(BUILD)/mktex tests/assets/grid.png

test: all
	./tests/run_tests.sh

golden: all
	VKMIN_WRITE_GOLDEN=1 ./tests/run_tests.sh

# A second analyser finds different things than the first; code clean under one
# routinely turns up real defects under another.
analyze:
	@command -v cppcheck >/dev/null || { echo "cppcheck not installed"; exit 1; }
	cppcheck --std=c11 --enable=warning,style,performance,portability \
	    --inline-suppr --error-exitcode=1 --quiet \
	    --suppress=missingIncludeSystem --suppress=missingInclude \
	    -Isrc -Idemo -I$(BUILD) -i third_party -i src/stb_bridge.c \
	    src demo tools tests

clean:
	rm -rf $(BUILD) tests/out
