#!/bin/sh
# Generates vkmin_single.h from the two-file source of truth. Never hand-edit
# the output; CI compiles it standalone. Usage: tools/amalgamate.sh > out.h
set -e
strip() { grep -vE '^#include "(vkmin|shared|cvar|plat|stb_bridge|vkmin_math|font|pack|spirv)\.h"' "$1"; }
echo "/* vkmin_single.h -- generated by tools/amalgamate.sh from src/; do not edit."
echo " * #define VKMIN_IMPLEMENTATION in exactly one translation unit before including."
echo " * The implementation includes stb_image.h and stb_image_write.h: have them on the include path. */"
echo "#ifndef VKMIN_SINGLE_H"
echo "#define VKMIN_SINGLE_H"
strip src/shared.h
strip src/vkmin.h
strip src/vkmin_math.h
strip src/pack.h
strip src/cvar.h
strip src/plat.h
echo "#endif /* VKMIN_SINGLE_H */"
echo "#ifdef VKMIN_IMPLEMENTATION"
strip src/cvar.c
strip src/stb_bridge.h
strip src/stb_bridge.c
echo "#ifndef VKMIN_NO_PLATFORM"
strip src/plat_glfw.c
echo "#endif"
strip src/spirv.h
strip src/vkmin.c
echo "#endif /* VKMIN_IMPLEMENTATION */"
