"""Run in Blender: export the reference rebuild in rest coordinates.

Articulation tags identify each turret's yaw housing and elevating barrels.
Linked portable scenes keep the same geometry; habitat rotation is runtime state.
"""
import bpy
from pathlib import Path
from mathutils import Vector, Matrix
from mathutils.bvhtree import BVHTree

ROOT = Path(__file__).resolve().parents[1]
SCENE = bpy.data.scenes['OMEGA | Reference rebuild']
MOUNTS = []
for sign in (-1, 1):
    MOUNTS.extend([((0, sign*1.50, z), (0, sign, 0)) for z in (-13.55, -.65, 3.45)])
    MOUNTS.extend([((sign*1.46, 0, z), (sign, 0, 0)) for z in (-13.55, -.65, 3.45)])
MOVING = {'turret armored breech': 0, 'turret trunnion': 0,
          'twin gun barrel': 1, 'gun muzzle lip': 1, 'gun bore': 1}
MATERIAL = {1:0, 2:1, 3:2, 4:0, 5:1, 6:2, 7:3, 8:4, 9:4, 10:0,
            11:7, 12:0, 13:4, 14:2, 15:3}

def export():
    vertices, triangles, rows = [], [], []
    parts = [0]*26
    for obj in sorted(SCENE.objects, key=lambda o:o.name):
        if obj.type != 'MESH' or 'omega_part' not in obj: continue
        mesh = obj.data
        mesh.calc_loop_triangles()
        transform = obj.matrix_local if obj.parent else obj.matrix_world
        normals = transform.to_3x3().inverted().transposed()
        group = MOVING.get(obj.name.removeprefix('Reference | Detail II '))
        for tri in mesh.loop_triangles:
            points = [transform @ mesh.vertices[i].co for i in tri.vertices]
            part = int(obj['omega_part'])
            if group is not None:
                center = sum(points, Vector())/3
                mount = min(range(12), key=lambda i:(center-Vector(MOUNTS[i][0])).length_squared)
                part = 2+2*mount+group
            parts[part] += 1
            mat = mesh.materials[tri.material_index]
            number = int(mat.name[:2])
            rgb = [round(max(0,min(1,c))*255) for c in mat.diffuse_color[:3]]
            triangles.append(tuple(range(len(vertices),len(vertices)+3)))
            vertices.extend(points)
            for point, loop in zip(points,tri.loops):
                normal = (normals @ mesh.corner_normals[loop].vector).normalized()
                xyz = [round(c*1000) for c in point]
                assert all(-32768 <= c <= 32767 for c in xyz)
                rows.append('{'+','.join(map(str,xyz+[round(c*32767) for c in normal]+rgb+[MATERIAL[number],part]))+'},\n')
    assert all(parts), parts
    output = ROOT/'omega/omega_model.h'
    output.write_text('/* Generated by tools/export_omega_blender.py; do not edit. */\n'
        '#include <stdint.h>\ntypedef struct { int16_t x,y,z,nx,ny,nz; uint8_t r,g,b,material,part; } OmegaPackedVertex;\n'
        f'#define OMEGA_MODEL_COUNT {len(rows)}u\n'
        'extern const OmegaPackedVertex omega_model[OMEGA_MODEL_COUNT];\n'
        '#ifdef OMEGA_MODEL_IMPLEMENTATION\nconst OmegaPackedVertex omega_model[OMEGA_MODEL_COUNT] = {\n'+''.join(rows)+'};\n#endif\n',encoding='utf-8')
    # Bake actual first surface contacts, not points guessed inside a bounding box.
    rotation = Matrix.Rotation(.8,3,'Y')
    enemy = BVHTree.FromPolygons([rotation @ v for v in vertices],triangles,all_triangles=True)
    hero = BVHTree.FromPolygons(vertices,triangles,all_triangles=True)
    beam = []
    for side in (-1,1):
        hit,normal,index,distance = enemy.ray_cast(Vector((side*2.39,.12,100)),Vector((0,0,-1)))
        assert hit is not None
        beam.append(tuple(hit))
    targets = []
    for offset in ((0,0,-190),(45,38,-240),(75,-26,-145)):
        origin = Vector(offset)+rotation @ Vector((-2.4,0,1.4))
        direction = (Vector((0,.12,-18))-origin).normalized()
        hit,normal,index,distance = hero.ray_cast(origin,direction)
        assert hit is not None
        targets.append(tuple(hit))
    def array(name, values):
        return 'static const vec3 '+name+'[] = {\n'+''.join('    {'+','.join(f'{c:.7f}f' for c in v)+'},\n' for v in values)+'};\n'
    (ROOT/'omega/omega_mounts.h').write_text('/* Generated model hardpoints and ray-cast armor contacts. */\n'
        '#define OMEGA_MUZZLE_X 2.39f\n#define OMEGA_MUZZLE_Y .12f\n#define OMEGA_MUZZLE_Z -20.105f\n'
        '#ifndef VKMIN_GLSL\n'+array('omega_mount', [p for p,n in MOUNTS])+
        array('omega_mount_normal',[n for p,n in MOUNTS])+array('omega_beam_contact',beam)+
        array('omega_pulse_contact',targets)+'#endif\n',encoding='utf-8')
    for i,(p,n) in enumerate(MOUNTS):
        name = f'Hardpoint | turret {i:02d}'
        marker = bpy.data.objects.get(name)
        if marker is None:
            marker = bpy.data.objects.new(name,None); SCENE.collection.objects.link(marker)
        marker.location=p; marker['normal']=n; marker['yaw_part']=2+2*i; marker['barrel_part']=3+2*i
        marker.empty_display_size=.25
    SCENE['native_triangles']=len(triangles)
    print('Exported',len(triangles),'triangles; parts:',parts,'; beam contacts:',beam,'; pulse contacts:',targets)

if __name__ == '__main__': export()
