"""Export the authored Blender collection to the native demo's packed mesh.

Run inside Blender. Millimetre positions and signed normalized normals preserve
the existing 48-byte GPU vertex format, procedural materials and rotation tags.
"""
import bpy
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
scene = bpy.data.scenes['OMEGA | Reference rebuild']
bpy.context.window.scene = scene
collection = bpy.data.collections['OMEGA | Agamemnon']
deps = bpy.context.evaluated_depsgraph_get()
rows=[]
for obj in sorted(collection.objects, key=lambda o:o.name):
    if obj.type not in ('MESH','FONT'): continue
    evaluated=obj.evaluated_get(deps)
    data=evaluated.to_mesh()
    data.calc_loop_triangles()
    # Ignore animated parent's rotation; native shader animates these vertices.
    transform=obj.matrix_basis
    normals=transform.to_3x3().inverted().transposed()
    for tri in data.loop_triangles:
        mat=data.materials[tri.material_index]
        color=tuple(round(max(0,min(1,v))*255) for v in mat.diffuse_color[:3])
        tag=int(mat.get('omega_material',0)); part=int(obj.get('omega_part',0))
        normal=(normals@tri.normal).normalized()
        n=tuple(round(v*32767) for v in normal)
        for index in tri.vertices:
            position=transform@data.vertices[index].co
            p=tuple(round(v*1000) for v in position)
            assert all(-32768<=v<=32767 for v in p), (obj.name,p)
            assert all(math.isfinite(v) for v in position)
            rows.append('{'+','.join(map(str,(*p,*n,*color,tag,part)))+'},\n')
    evaluated.to_mesh_clear()
header='''/* Generated by tools/export_omega_blender.py from omega_destroyer.blend.
 * Edit the Blender source, then regenerate; do not hand-edit this array. */
#ifndef OMEGA_MODEL_H
#define OMEGA_MODEL_H
typedef struct { int16_t x,y,z,nx,ny,nz; uint8_t r,g,b,material,part; } OmegaPackedVertex;
static const OmegaPackedVertex omega_model[] = {
'''+''.join(rows)+'''};
#define OMEGA_MODEL_COUNT (sizeof omega_model / sizeof omega_model[0])
#endif
'''
(ROOT/'demo/omega_model.h').write_text(header,encoding='utf-8')
print('Exported',len(rows),'vertices,',len(rows)//3,'triangles')
