/* mkfont -- bakes a monospace TrueType font into a C header at build time:
 * an 8-bit coverage atlas plus per-glyph rectangles for ASCII 32..126. The
 * overlay then has no font file to fail to find.
 *   mkfont <font.ttf> <pixel height> > font.h */
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#include <stdio.h>
#include <stdlib.h>

enum { ATLAS_W = 256, ATLAS_H = 128, FIRST = 32, COUNT = 95 };

int main(int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: mkfont <font.ttf> <pixel height>\n");
        return 2;
    }
    FILE *f = fopen(argv[1], "rb");
    if (!f) { fprintf(stderr, "mkfont: cannot open %s\n", argv[1]); return 1; }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    unsigned char *ttf = malloc((size_t)size);
    const size_t got = ttf ? fread(ttf, 1, (size_t)size, f) : 0;
    fclose(f);
    if (got != (size_t)size) { fprintf(stderr, "mkfont: read failed\n"); free(ttf); return 1; }

    unsigned char *atlas = calloc(ATLAS_W * ATLAS_H, 1);
    stbtt_bakedchar glyphs[COUNT];
    const float px = (float)atof(argv[2]);
    const int rows = stbtt_BakeFontBitmap(ttf, 0, px, atlas, ATLAS_W, ATLAS_H, FIRST, COUNT, glyphs);
    if (rows <= 0) { fprintf(stderr, "mkfont: atlas too small\n"); return 1; }

    printf("/* generated by tools/mkfont from %s at %spx; do not edit */\n", argv[1], argv[2]);
    printf("#ifndef VKMIN_FONT_H\n#define VKMIN_FONT_H\n#include <stdint.h>\n");
    printf("enum { FONT_ATLAS_W = %d, FONT_ATLAS_H = %d, FONT_FIRST = %d, FONT_COUNT = %d };\n", ATLAS_W, ATLAS_H, FIRST, COUNT);
    printf("static const float FONT_LINE_HEIGHT = %.1ff;\n", (double)px);
    printf("typedef struct { uint16_t x0, y0, x1, y1; float xoff, yoff, xadvance; } font_glyph;\n");
    printf("static const font_glyph FONT_GLYPHS[FONT_COUNT] = {\n");
    for (int i = 0; i < COUNT; ++i) {
        printf("    {%u, %u, %u, %u, %.3ff, %.3ff, %.3ff},\n", glyphs[i].x0, glyphs[i].y0, glyphs[i].x1, glyphs[i].y1,
               (double)glyphs[i].xoff, (double)glyphs[i].yoff, (double)glyphs[i].xadvance);
    }
    printf("};\nstatic const uint8_t FONT_ATLAS[FONT_ATLAS_W * FONT_ATLAS_H] = {\n");
    for (int i = 0; i < ATLAS_W * ATLAS_H; ++i) printf("%u,%s", atlas[i], (i % 32 == 31) ? "\n" : "");
    printf("};\n#endif\n");
    return 0;
}
