/* mkfont -- bakes a monospace TrueType font into a C header at build time as
 * a signed distance field: an 8-bit atlas where 128 is the glyph edge and
 * each step is 1/FONT_SDF_SCALE of a texel, plus per-glyph rectangles for
 * ASCII 32..126. A distance field scales: the same atlas draws 8px HUD text
 * and 200px titles with clean edges, which a coverage bitmap cannot.
 *   mkfont <font.ttf> <pixel height> > font.h */
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#include <stdio.h>
#include <stdlib.h>

enum { ATLAS_W = 512, ATLAS_H = 256, FIRST = 32, COUNT = 95, PAD = 4, ONEDGE = 128, SDF_SCALE = 24 };

typedef struct { int x0, y0, x1, y1, xoff, yoff; float xadvance; } glyph;

int main(int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: mkfont <font.ttf> <pixel height>\n");
        return 2;
    }
    FILE *f = fopen(argv[1], "rb");
    if (!f) { fprintf(stderr, "mkfont: cannot open %s\n", argv[1]); return 1; }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    unsigned char *ttf = malloc((size_t)size);
    const size_t got = ttf ? fread(ttf, 1, (size_t)size, f) : 0;
    fclose(f);
    if (got != (size_t)size) { fprintf(stderr, "mkfont: read failed\n"); free(ttf); return 1; }

    stbtt_fontinfo info;
    if (!stbtt_InitFont(&info, ttf, 0)) { fprintf(stderr, "mkfont: not a TrueType font\n"); free(ttf); return 1; }
    const float px = (float)atof(argv[2]);
    const float scale = stbtt_ScaleForPixelHeight(&info, px);
    unsigned char *atlas = calloc((size_t)ATLAS_W * ATLAS_H, 1);
    if (!atlas) { free(ttf); return 1; }
    glyph glyphs[COUNT];
    /* Shelf packing: left to right, a new row when a glyph does not fit. */
    int x = 1, y = 1, row_h = 0;
    for (int i = 0; i < COUNT; ++i) {
        int w = 0, h = 0, xoff = 0, yoff = 0;
        unsigned char *sdf = stbtt_GetCodepointSDF(&info, scale, FIRST + i, PAD, ONEDGE, (float)SDF_SCALE, &w, &h, &xoff, &yoff);
        int advance = 0, lsb = 0;
        stbtt_GetCodepointHMetrics(&info, FIRST + i, &advance, &lsb);
        if (x + w + 1 > ATLAS_W) { x = 1; y += row_h + 1; row_h = 0; }
        if (y + h + 1 > ATLAS_H) { fprintf(stderr, "mkfont: atlas too small\n"); return 1; }
        for (int r = 0; r < h; ++r) {
            for (int c = 0; c < w; ++c) atlas[(y + r) * ATLAS_W + x + c] = sdf[r * w + c];
        }
        glyphs[i] = (glyph){x, y, x + w, y + h, xoff, yoff, (float)advance * scale};
        x += w + 1;
        row_h = h > row_h ? h : row_h;
        if (sdf) stbtt_FreeSDF(sdf, NULL);
    }

    printf("/* generated by tools/mkfont from %s at %spx as a signed distance field; do not edit */\n", argv[1], argv[2]);
    printf("#ifndef VKMIN_FONT_H\n#define VKMIN_FONT_H\n#include <stdint.h>\n");
    printf("enum { FONT_ATLAS_W = %d, FONT_ATLAS_H = %d, FONT_FIRST = %d, FONT_COUNT = %d, FONT_SDF_SCALE = %d };\n",
           ATLAS_W, ATLAS_H, FIRST, COUNT, SDF_SCALE);
    printf("static const float FONT_PX = %.1ff; /* the baked size; metrics below are in its pixels */\n", (double)px);
    printf("typedef struct { uint16_t x0, y0, x1, y1; float xoff, yoff, xadvance; } font_glyph;\n");
    printf("static const font_glyph FONT_GLYPHS[FONT_COUNT] = {\n");
    for (int i = 0; i < COUNT; ++i) {
        printf("    {%d, %d, %d, %d, %d.0f, %d.0f, %.3ff},\n", glyphs[i].x0, glyphs[i].y0, glyphs[i].x1, glyphs[i].y1,
               glyphs[i].xoff, glyphs[i].yoff, (double)glyphs[i].xadvance);
    }
    printf("};\nstatic const uint8_t FONT_ATLAS[FONT_ATLAS_W * FONT_ATLAS_H] = {\n");
    for (int i = 0; i < ATLAS_W * ATLAS_H; ++i) printf("%u,%s", atlas[i], (i % 64 == 63) ? "\n" : "");
    printf("};\n#endif\n");
    free(atlas);
    free(ttf);
    return 0;
}
