# Turn compiled SPIR-V into a C header of uint32_t arrays.
#
# Invoked by the build as:
#   cmake -DOUTPUT=<header> "-DSPIRV=<a.spv;b.spv;...>" -P embed_spirv.cmake
#
# This replaces the bin2c host tool the make build used. Doing it in CMake
# keeps the shader step free of a bootstrap binary, which is one fewer thing
# that can be stale or missing when the build is run somewhere new.

if(NOT DEFINED OUTPUT OR NOT DEFINED SPIRV)
    message(FATAL_ERROR "embed_spirv.cmake requires -DOUTPUT= and -DSPIRV=")
endif()

set(body "/* generated by the build from src/shaders; do not edit */\n")
string(APPEND body "#ifndef VKMIN_SHADERS_H\n#define VKMIN_SHADERS_H\n#include <stdint.h>\n\n")

foreach(spv IN LISTS SPIRV)
    # omega_hull.frag.spv -> omega_hull_frag_spv, the name the C side already uses.
    get_filename_component(stem "${spv}" NAME)
    string(REGEX REPLACE "\.spv$" "" stem "${stem}")
    string(REPLACE "." "_" symbol "${stem}")

    file(READ "${spv}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR tail "${hexlen} % 8")
    if(hexlen EQUAL 0 OR NOT tail EQUAL 0)
        message(FATAL_ERROR "${spv}: ${hexlen} hex digits is not a whole number of 32-bit words")
    endif()

    # One pass over the whole file: every little-endian 4-byte group becomes
    # one word. A per-word CMake loop would take seconds on a 100 KB module.
    string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," words "${hex}")
    # Eight to a line, so a regenerated header still diffs readably.
    string(REGEX REPLACE "((0x[0-9a-f]+u,){8})" "\\1\n    " words "${words}")

    # static: src/render.c and omega/omega.c both include this header and can
    # end up in the same link.
    string(APPEND body "static const uint32_t ${symbol}_spv[] = {\n    ${words}\n};\n\n")
endforeach()

string(APPEND body "#endif\n")
file(WRITE "${OUTPUT}" "${body}")
